import "../styles/globals.css";

import { ThemeProvider } from '@/components/ThemeProvider';
import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';

export const raleway = Raleway({
  subsets: ['latin'],
  variable: '--raleway-font',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" className={raleway.variable}>
      <body className="font-raleway">
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
